name: Auto-Merge and Delete Branch
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main # The branch you want to merge INTO
jobs:
  auto-merge:
    # Bypasses drafts and only runs when the PR is ready for review
    # if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Enable Auto-Merge and Delete Branch
        run: gh pr merge "$PR_URL" --auto --squash --delete-branch
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
